/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const WorkoutId = IDL.Nat;
export const PostId = IDL.Nat;
export const Coordinate = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ZoneId = IDL.Nat;
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const ChallengeType = IDL.Variant({
  'mostDistance' : IDL.Null,
  'mostTakedowns' : IDL.Null,
  'mostWorkouts' : IDL.Null,
  'mostTerritory' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const CompetitionId = IDL.Nat;
export const WorkoutStatus = IDL.Variant({
  'completed' : IDL.Null,
  'abandoned' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const UserId = IDL.Principal;
export const WorkoutType = IDL.Variant({
  'run' : IDL.Null,
  'other' : IDL.Null,
  'hiit' : IDL.Null,
  'yoga' : IDL.Null,
  'strength' : IDL.Null,
  'walking' : IDL.Null,
  'cycling' : IDL.Null,
});
export const WorkoutSummary = IDL.Record({
  'id' : WorkoutId,
  'status' : WorkoutStatus,
  'completedAt' : IDL.Opt(Timestamp),
  'startedAt' : Timestamp,
  'userId' : UserId,
  'territoryZonesClaimed' : IDL.Nat,
  'durationSeconds' : IDL.Nat,
  'caloriesBurned' : IDL.Opt(IDL.Float64),
  'averagePaceSecondsPerKm' : IDL.Opt(IDL.Float64),
  'distanceMetres' : IDL.Float64,
  'workoutType' : WorkoutType,
});
export const FitnessLevel = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
  'elite' : IDL.Null,
});
export const Standing = IDL.Record({
  'userId' : UserId,
  'rank' : IDL.Nat,
  'score' : IDL.Float64,
});
export const CompetitionView = IDL.Record({
  'id' : CompetitionId,
  'startsAt' : Timestamp,
  'standings' : IDL.Vec(Standing),
  'isActive' : IDL.Bool,
  'challengeType' : ChallengeType,
  'prizes' : IDL.Vec(IDL.Text),
  'monthYear' : IDL.Text,
  'endsAt' : Timestamp,
});
export const CoachMessageId = IDL.Nat;
export const MessageRole = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const CoachMessage = IDL.Record({
  'id' : CoachMessageId,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : MessageRole,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'author' : UserId,
});
export const PostView = IDL.Record({
  'id' : PostId,
  'createdAt' : Timestamp,
  'likedBy' : IDL.Vec(UserId),
  'author' : UserId,
  'message' : IDL.Text,
  'territoryClaimed' : IDL.Vec(ZoneId),
  'commentsCount' : IDL.Nat,
  'comments' : IDL.Vec(Comment),
  'likesCount' : IDL.Nat,
  'workoutSummary' : IDL.Opt(WorkoutSummary),
});
export const LeaderboardEntry = IDL.Record({
  'username' : IDL.Text,
  'userId' : UserId,
  'rank' : IDL.Nat,
  'totalTerritoryArea' : IDL.Float64,
  'locationLabel' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Opt(IDL.Text),
  'fitnessLevel' : FitnessLevel,
  'weeklyAvailabilityHours' : IDL.Nat,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'followersCount' : IDL.Nat,
  'joinedAt' : Timestamp,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'totalTerritoryArea' : IDL.Float64,
  'locationLabel' : IDL.Text,
  'followingCount' : IDL.Nat,
});
export const TakeoverEvent = IDL.Record({
  'newOwner' : UserId,
  'workoutId' : WorkoutId,
  'previousOwner' : IDL.Opt(UserId),
  'takenAt' : Timestamp,
});
export const ZoneInfo = IDL.Record({
  'id' : ZoneId,
  'polygon' : IDL.Vec(Coordinate),
  'owner' : IDL.Opt(UserId),
  'name' : IDL.Text,
  'workoutId' : IDL.Opt(WorkoutId),
  'claimedAt' : IDL.Opt(Timestamp),
  'areaKm2' : IDL.Float64,
  'takeoverHistory' : IDL.Vec(TakeoverEvent),
});
export const GpsEvent = IDL.Record({
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'eventType' : IDL.Text,
  'accuracy' : IDL.Opt(IDL.Float64),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'abandonWorkout' : IDL.Func([WorkoutId], [IDL.Bool], []),
  'addComment' : IDL.Func([PostId, IDL.Text], [IDL.Bool], []),
  'appendGpsPoint' : IDL.Func([WorkoutId, Coordinate], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimZone' : IDL.Func([ZoneId, WorkoutId], [IDL.Bool], []),
  'clearConversation' : IDL.Func([], [IDL.Bool], []),
  'coachTransform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'completeWorkout' : IDL.Func(
      [
        WorkoutId,
        IDL.Float64,
        IDL.Nat,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
      ],
      [IDL.Bool],
      [],
    ),
  'createCompetition' : IDL.Func(
      [IDL.Text, ChallengeType, IDL.Vec(IDL.Text), Timestamp, Timestamp],
      [CompetitionId],
      [],
    ),
  'createPost' : IDL.Func(
      [IDL.Opt(WorkoutSummary), IDL.Vec(ZoneId), IDL.Text],
      [PostId],
      [],
    ),
  'createProfile' : IDL.Func(
      [IDL.Text, IDL.Text, FitnessLevel, IDL.Text, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'createZone' : IDL.Func(
      [IDL.Text, IDL.Vec(Coordinate), IDL.Float64],
      [ZoneId],
      [],
    ),
  'deletePost' : IDL.Func([PostId], [IDL.Bool], []),
  'follow' : IDL.Func([UserId], [IDL.Bool], []),
  'getActiveCompetition' : IDL.Func([], [IDL.Opt(CompetitionView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoachConversation' : IDL.Func([], [IDL.Vec(CoachMessage)], ['query']),
  'getCoachHistory' : IDL.Func([], [IDL.Vec(CoachMessage)], ['query']),
  'getCompetition' : IDL.Func(
      [CompetitionId],
      [IDL.Opt(CompetitionView)],
      ['query'],
    ),
  'getCompetitionLeaderboard' : IDL.Func(
      [CompetitionId],
      [IDL.Vec(Standing)],
      [],
    ),
  'getFollowers' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
  'getFollowing' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
  'getGlobalFeed' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(PostView)],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Nat],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getMyFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(PostView)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMyWorkouts' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(WorkoutSummary)],
      ['query'],
    ),
  'getPost' : IDL.Func([PostId], [IDL.Opt(PostView)], ['query']),
  'getProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getUserWorkouts' : IDL.Func(
      [UserId, IDL.Nat, IDL.Nat],
      [IDL.Vec(WorkoutSummary)],
      ['query'],
    ),
  'getWorkout' : IDL.Func([WorkoutId], [IDL.Opt(WorkoutSummary)], ['query']),
  'getWorkoutRoute' : IDL.Func(
      [WorkoutId],
      [IDL.Opt(IDL.Vec(Coordinate))],
      ['query'],
    ),
  'getZone' : IDL.Func([ZoneId], [IDL.Opt(ZoneInfo)], ['query']),
  'getZoneHistory' : IDL.Func([ZoneId], [IDL.Vec(TakeoverEvent)], ['query']),
  'getZoneLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(UserId, IDL.Float64))],
      ['query'],
    ),
  'getZonesInBounds' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Vec(ZoneInfo)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinCompetition' : IDL.Func([CompetitionId], [IDL.Bool], []),
  'likePost' : IDL.Func([PostId], [IDL.Bool], []),
  'listCompetitions' : IDL.Func([], [IDL.Vec(CompetitionView)], ['query']),
  'listZones' : IDL.Func([IDL.Opt(UserId)], [IDL.Vec(ZoneInfo)], ['query']),
  'logGpsEvent' : IDL.Func([WorkoutId, GpsEvent], [IDL.Bool], []),
  'sendCoachMessage' : IDL.Func([IDL.Text], [IDL.Text], []),
  'startCoachSession' : IDL.Func([], [IDL.Vec(CoachMessage)], []),
  'startWorkout' : IDL.Func([WorkoutType], [WorkoutId], []),
  'unfollow' : IDL.Func([UserId], [IDL.Bool], []),
  'unlikePost' : IDL.Func([PostId], [IDL.Bool], []),
  'updateProfile' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(FitnessLevel),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const WorkoutId = IDL.Nat;
  const PostId = IDL.Nat;
  const Coordinate = IDL.Record({ 'lat' : IDL.Float64, 'lng' : IDL.Float64 });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ZoneId = IDL.Nat;
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const ChallengeType = IDL.Variant({
    'mostDistance' : IDL.Null,
    'mostTakedowns' : IDL.Null,
    'mostWorkouts' : IDL.Null,
    'mostTerritory' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const CompetitionId = IDL.Nat;
  const WorkoutStatus = IDL.Variant({
    'completed' : IDL.Null,
    'abandoned' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const WorkoutType = IDL.Variant({
    'run' : IDL.Null,
    'other' : IDL.Null,
    'hiit' : IDL.Null,
    'yoga' : IDL.Null,
    'strength' : IDL.Null,
    'walking' : IDL.Null,
    'cycling' : IDL.Null,
  });
  const WorkoutSummary = IDL.Record({
    'id' : WorkoutId,
    'status' : WorkoutStatus,
    'completedAt' : IDL.Opt(Timestamp),
    'startedAt' : Timestamp,
    'userId' : UserId,
    'territoryZonesClaimed' : IDL.Nat,
    'durationSeconds' : IDL.Nat,
    'caloriesBurned' : IDL.Opt(IDL.Float64),
    'averagePaceSecondsPerKm' : IDL.Opt(IDL.Float64),
    'distanceMetres' : IDL.Float64,
    'workoutType' : WorkoutType,
  });
  const FitnessLevel = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
    'elite' : IDL.Null,
  });
  const Standing = IDL.Record({
    'userId' : UserId,
    'rank' : IDL.Nat,
    'score' : IDL.Float64,
  });
  const CompetitionView = IDL.Record({
    'id' : CompetitionId,
    'startsAt' : Timestamp,
    'standings' : IDL.Vec(Standing),
    'isActive' : IDL.Bool,
    'challengeType' : ChallengeType,
    'prizes' : IDL.Vec(IDL.Text),
    'monthYear' : IDL.Text,
    'endsAt' : Timestamp,
  });
  const CoachMessageId = IDL.Nat;
  const MessageRole = IDL.Variant({
    'user' : IDL.Null,
    'assistant' : IDL.Null,
  });
  const CoachMessage = IDL.Record({
    'id' : CoachMessageId,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : MessageRole,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'author' : UserId,
  });
  const PostView = IDL.Record({
    'id' : PostId,
    'createdAt' : Timestamp,
    'likedBy' : IDL.Vec(UserId),
    'author' : UserId,
    'message' : IDL.Text,
    'territoryClaimed' : IDL.Vec(ZoneId),
    'commentsCount' : IDL.Nat,
    'comments' : IDL.Vec(Comment),
    'likesCount' : IDL.Nat,
    'workoutSummary' : IDL.Opt(WorkoutSummary),
  });
  const LeaderboardEntry = IDL.Record({
    'username' : IDL.Text,
    'userId' : UserId,
    'rank' : IDL.Nat,
    'totalTerritoryArea' : IDL.Float64,
    'locationLabel' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Opt(IDL.Text),
    'fitnessLevel' : FitnessLevel,
    'weeklyAvailabilityHours' : IDL.Nat,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'followersCount' : IDL.Nat,
    'joinedAt' : Timestamp,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'totalTerritoryArea' : IDL.Float64,
    'locationLabel' : IDL.Text,
    'followingCount' : IDL.Nat,
  });
  const TakeoverEvent = IDL.Record({
    'newOwner' : UserId,
    'workoutId' : WorkoutId,
    'previousOwner' : IDL.Opt(UserId),
    'takenAt' : Timestamp,
  });
  const ZoneInfo = IDL.Record({
    'id' : ZoneId,
    'polygon' : IDL.Vec(Coordinate),
    'owner' : IDL.Opt(UserId),
    'name' : IDL.Text,
    'workoutId' : IDL.Opt(WorkoutId),
    'claimedAt' : IDL.Opt(Timestamp),
    'areaKm2' : IDL.Float64,
    'takeoverHistory' : IDL.Vec(TakeoverEvent),
  });
  const GpsEvent = IDL.Record({
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'eventType' : IDL.Text,
    'accuracy' : IDL.Opt(IDL.Float64),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'abandonWorkout' : IDL.Func([WorkoutId], [IDL.Bool], []),
    'addComment' : IDL.Func([PostId, IDL.Text], [IDL.Bool], []),
    'appendGpsPoint' : IDL.Func([WorkoutId, Coordinate], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimZone' : IDL.Func([ZoneId, WorkoutId], [IDL.Bool], []),
    'clearConversation' : IDL.Func([], [IDL.Bool], []),
    'coachTransform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'completeWorkout' : IDL.Func(
        [
          WorkoutId,
          IDL.Float64,
          IDL.Nat,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
        ],
        [IDL.Bool],
        [],
      ),
    'createCompetition' : IDL.Func(
        [IDL.Text, ChallengeType, IDL.Vec(IDL.Text), Timestamp, Timestamp],
        [CompetitionId],
        [],
      ),
    'createPost' : IDL.Func(
        [IDL.Opt(WorkoutSummary), IDL.Vec(ZoneId), IDL.Text],
        [PostId],
        [],
      ),
    'createProfile' : IDL.Func(
        [IDL.Text, IDL.Text, FitnessLevel, IDL.Text, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'createZone' : IDL.Func(
        [IDL.Text, IDL.Vec(Coordinate), IDL.Float64],
        [ZoneId],
        [],
      ),
    'deletePost' : IDL.Func([PostId], [IDL.Bool], []),
    'follow' : IDL.Func([UserId], [IDL.Bool], []),
    'getActiveCompetition' : IDL.Func(
        [],
        [IDL.Opt(CompetitionView)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoachConversation' : IDL.Func([], [IDL.Vec(CoachMessage)], ['query']),
    'getCoachHistory' : IDL.Func([], [IDL.Vec(CoachMessage)], ['query']),
    'getCompetition' : IDL.Func(
        [CompetitionId],
        [IDL.Opt(CompetitionView)],
        ['query'],
      ),
    'getCompetitionLeaderboard' : IDL.Func(
        [CompetitionId],
        [IDL.Vec(Standing)],
        [],
      ),
    'getFollowers' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
    'getFollowing' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
    'getGlobalFeed' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(PostView)],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Nat],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getMyFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(PostView)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMyWorkouts' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(WorkoutSummary)],
        ['query'],
      ),
    'getPost' : IDL.Func([PostId], [IDL.Opt(PostView)], ['query']),
    'getProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getUserWorkouts' : IDL.Func(
        [UserId, IDL.Nat, IDL.Nat],
        [IDL.Vec(WorkoutSummary)],
        ['query'],
      ),
    'getWorkout' : IDL.Func([WorkoutId], [IDL.Opt(WorkoutSummary)], ['query']),
    'getWorkoutRoute' : IDL.Func(
        [WorkoutId],
        [IDL.Opt(IDL.Vec(Coordinate))],
        ['query'],
      ),
    'getZone' : IDL.Func([ZoneId], [IDL.Opt(ZoneInfo)], ['query']),
    'getZoneHistory' : IDL.Func([ZoneId], [IDL.Vec(TakeoverEvent)], ['query']),
    'getZoneLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(UserId, IDL.Float64))],
        ['query'],
      ),
    'getZonesInBounds' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Vec(ZoneInfo)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinCompetition' : IDL.Func([CompetitionId], [IDL.Bool], []),
    'likePost' : IDL.Func([PostId], [IDL.Bool], []),
    'listCompetitions' : IDL.Func([], [IDL.Vec(CompetitionView)], ['query']),
    'listZones' : IDL.Func([IDL.Opt(UserId)], [IDL.Vec(ZoneInfo)], ['query']),
    'logGpsEvent' : IDL.Func([WorkoutId, GpsEvent], [IDL.Bool], []),
    'sendCoachMessage' : IDL.Func([IDL.Text], [IDL.Text], []),
    'startCoachSession' : IDL.Func([], [IDL.Vec(CoachMessage)], []),
    'startWorkout' : IDL.Func([WorkoutType], [WorkoutId], []),
    'unfollow' : IDL.Func([UserId], [IDL.Bool], []),
    'unlikePost' : IDL.Func([PostId], [IDL.Bool], []),
    'updateProfile' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(FitnessLevel),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };