/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ChallengeType = { 'mostDistance' : null } |
  { 'mostTakedowns' : null } |
  { 'mostWorkouts' : null } |
  { 'mostTerritory' : null };
export interface CoachMessage {
  'id' : CoachMessageId,
  'content' : string,
  'createdAt' : Timestamp,
  'role' : MessageRole,
}
export type CoachMessageId = bigint;
export interface Comment {
  'id' : bigint,
  'content' : string,
  'createdAt' : Timestamp,
  'author' : UserId,
}
export type CompetitionId = bigint;
export interface CompetitionView {
  'id' : CompetitionId,
  'startsAt' : Timestamp,
  'standings' : Array<Standing>,
  'isActive' : boolean,
  'challengeType' : ChallengeType,
  'prizes' : Array<string>,
  'monthYear' : string,
  'endsAt' : Timestamp,
}
export interface Coordinate { 'lat' : number, 'lng' : number }
export type FitnessLevel = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null } |
  { 'elite' : null };
export interface GpsEvent {
  'message' : string,
  'timestamp' : Timestamp,
  'eventType' : string,
  'accuracy' : [] | [number],
}
export interface LeaderboardEntry {
  'username' : string,
  'userId' : UserId,
  'rank' : bigint,
  'totalTerritoryArea' : number,
  'locationLabel' : string,
}
export type MessageRole = { 'user' : null } |
  { 'assistant' : null };
export type PostId = bigint;
export interface PostView {
  'id' : PostId,
  'createdAt' : Timestamp,
  'likedBy' : Array<UserId>,
  'author' : UserId,
  'message' : string,
  'territoryClaimed' : Array<ZoneId>,
  'commentsCount' : bigint,
  'comments' : Array<Comment>,
  'likesCount' : bigint,
  'workoutSummary' : [] | [WorkoutSummary],
}
export interface Standing {
  'userId' : UserId,
  'rank' : bigint,
  'score' : number,
}
export interface TakeoverEvent {
  'newOwner' : UserId,
  'workoutId' : WorkoutId,
  'previousOwner' : [] | [UserId],
  'takenAt' : Timestamp,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'bio' : [] | [string],
  'fitnessLevel' : FitnessLevel,
  'weeklyAvailabilityHours' : bigint,
  'username' : string,
  'displayName' : string,
  'followersCount' : bigint,
  'joinedAt' : Timestamp,
  'avatarUrl' : [] | [string],
  'totalTerritoryArea' : number,
  'locationLabel' : string,
  'followingCount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type WorkoutId = bigint;
export type WorkoutStatus = { 'completed' : null } |
  { 'abandoned' : null } |
  { 'inProgress' : null };
export interface WorkoutSummary {
  'id' : WorkoutId,
  'status' : WorkoutStatus,
  'completedAt' : [] | [Timestamp],
  'startedAt' : Timestamp,
  'userId' : UserId,
  'territoryZonesClaimed' : bigint,
  'durationSeconds' : bigint,
  'caloriesBurned' : [] | [number],
  'averagePaceSecondsPerKm' : [] | [number],
  'distanceMetres' : number,
  'workoutType' : WorkoutType,
}
export type WorkoutType = { 'run' : null } |
  { 'other' : null } |
  { 'hiit' : null } |
  { 'yoga' : null } |
  { 'strength' : null } |
  { 'walking' : null } |
  { 'cycling' : null };
export type ZoneId = bigint;
export interface ZoneInfo {
  'id' : ZoneId,
  'polygon' : Array<Coordinate>,
  'owner' : [] | [UserId],
  'name' : string,
  'workoutId' : [] | [WorkoutId],
  'claimedAt' : [] | [Timestamp],
  'areaKm2' : number,
  'takeoverHistory' : Array<TakeoverEvent>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'abandonWorkout' : ActorMethod<[WorkoutId], boolean>,
  'addComment' : ActorMethod<[PostId, string], boolean>,
  'appendGpsPoint' : ActorMethod<[WorkoutId, Coordinate], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimZone' : ActorMethod<[ZoneId, WorkoutId], boolean>,
  'clearConversation' : ActorMethod<[], boolean>,
  'coachTransform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'completeWorkout' : ActorMethod<
    [WorkoutId, number, bigint, [] | [number], [] | [number], [] | [number]],
    boolean
  >,
  'createCompetition' : ActorMethod<
    [string, ChallengeType, Array<string>, Timestamp, Timestamp],
    CompetitionId
  >,
  'createPost' : ActorMethod<
    [[] | [WorkoutSummary], Array<ZoneId>, string],
    PostId
  >,
  'createProfile' : ActorMethod<
    [string, string, FitnessLevel, string, bigint],
    boolean
  >,
  'createZone' : ActorMethod<[string, Array<Coordinate>, number], ZoneId>,
  'deletePost' : ActorMethod<[PostId], boolean>,
  'follow' : ActorMethod<[UserId], boolean>,
  'getActiveCompetition' : ActorMethod<[], [] | [CompetitionView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoachConversation' : ActorMethod<[], Array<CoachMessage>>,
  'getCoachHistory' : ActorMethod<[], Array<CoachMessage>>,
  'getCompetition' : ActorMethod<[CompetitionId], [] | [CompetitionView]>,
  'getCompetitionLeaderboard' : ActorMethod<[CompetitionId], Array<Standing>>,
  'getFollowers' : ActorMethod<[UserId], Array<UserId>>,
  'getFollowing' : ActorMethod<[UserId], Array<UserId>>,
  'getGlobalFeed' : ActorMethod<[bigint, bigint], Array<PostView>>,
  'getLeaderboard' : ActorMethod<
    [[] | [string], bigint],
    Array<LeaderboardEntry>
  >,
  'getMyFeed' : ActorMethod<[bigint, bigint], Array<PostView>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMyWorkouts' : ActorMethod<[bigint, bigint], Array<WorkoutSummary>>,
  'getPost' : ActorMethod<[PostId], [] | [PostView]>,
  'getProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getUserWorkouts' : ActorMethod<
    [UserId, bigint, bigint],
    Array<WorkoutSummary>
  >,
  'getWorkout' : ActorMethod<[WorkoutId], [] | [WorkoutSummary]>,
  'getWorkoutRoute' : ActorMethod<[WorkoutId], [] | [Array<Coordinate>]>,
  'getZone' : ActorMethod<[ZoneId], [] | [ZoneInfo]>,
  'getZoneHistory' : ActorMethod<[ZoneId], Array<TakeoverEvent>>,
  'getZoneLeaderboard' : ActorMethod<[], Array<[UserId, number]>>,
  'getZonesInBounds' : ActorMethod<
    [number, number, number, number],
    Array<ZoneInfo>
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinCompetition' : ActorMethod<[CompetitionId], boolean>,
  'likePost' : ActorMethod<[PostId], boolean>,
  'listCompetitions' : ActorMethod<[], Array<CompetitionView>>,
  'listZones' : ActorMethod<[[] | [UserId]], Array<ZoneInfo>>,
  'logGpsEvent' : ActorMethod<[WorkoutId, GpsEvent], boolean>,
  'sendCoachMessage' : ActorMethod<[string], string>,
  'startCoachSession' : ActorMethod<[], Array<CoachMessage>>,
  'startWorkout' : ActorMethod<[WorkoutType], WorkoutId>,
  'unfollow' : ActorMethod<[UserId], boolean>,
  'unlikePost' : ActorMethod<[PostId], boolean>,
  'updateProfile' : ActorMethod<
    [
      [] | [string],
      [] | [FitnessLevel],
      [] | [string],
      [] | [bigint],
      [] | [string],
      [] | [string],
    ],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];