/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaderboardEntry {
    username: string;
    userId: UserId;
    rank: bigint;
    totalTerritoryArea: number;
    locationLabel: string;
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type PostId = bigint;
export interface PostView {
    id: PostId;
    createdAt: Timestamp;
    likedBy: Array<UserId>;
    author: UserId;
    message: string;
    territoryClaimed: Array<ZoneId>;
    commentsCount: bigint;
    comments: Array<Comment>;
    likesCount: bigint;
    workoutSummary?: WorkoutSummary;
}
export type CompetitionId = bigint;
export type ZoneId = bigint;
export interface TakeoverEvent {
    newOwner: UserId;
    workoutId: WorkoutId;
    previousOwner?: UserId;
    takenAt: Timestamp;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface GpsEvent {
    message: string;
    timestamp: Timestamp;
    eventType: string;
    accuracy?: number;
}
export interface CompetitionView {
    id: CompetitionId;
    startsAt: Timestamp;
    standings: Array<Standing>;
    isActive: boolean;
    challengeType: ChallengeType;
    prizes: Array<string>;
    monthYear: string;
    endsAt: Timestamp;
}
export interface Comment {
    id: bigint;
    content: string;
    createdAt: Timestamp;
    author: UserId;
}
export interface Standing {
    userId: UserId;
    rank: bigint;
    score: number;
}
export interface Coordinate {
    lat: number;
    lng: number;
}
export type WorkoutId = bigint;
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type UserId = Principal;
export interface WorkoutSummary {
    id: WorkoutId;
    status: WorkoutStatus;
    completedAt?: Timestamp;
    startedAt: Timestamp;
    userId: UserId;
    territoryZonesClaimed: bigint;
    durationSeconds: bigint;
    caloriesBurned?: number;
    averagePaceSecondsPerKm?: number;
    distanceMetres: number;
    workoutType: WorkoutType;
}
export interface ZoneInfo {
    id: ZoneId;
    polygon: Array<Coordinate>;
    owner?: UserId;
    name: string;
    workoutId?: WorkoutId;
    claimedAt?: Timestamp;
    areaKm2: number;
    takeoverHistory: Array<TakeoverEvent>;
}
export interface CoachMessage {
    id: CoachMessageId;
    content: string;
    createdAt: Timestamp;
    role: MessageRole;
}
export interface UserProfile {
    id: UserId;
    bio?: string;
    fitnessLevel: FitnessLevel;
    weeklyAvailabilityHours: bigint;
    username: string;
    displayName: string;
    followersCount: bigint;
    joinedAt: Timestamp;
    avatarUrl?: string;
    totalTerritoryArea: number;
    locationLabel: string;
    followingCount: bigint;
}
export type CoachMessageId = bigint;
export enum ChallengeType {
    mostDistance = "mostDistance",
    mostTakedowns = "mostTakedowns",
    mostWorkouts = "mostWorkouts",
    mostTerritory = "mostTerritory"
}
export enum FitnessLevel {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced",
    elite = "elite"
}
export enum MessageRole {
    user = "user",
    assistant = "assistant"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WorkoutStatus {
    completed = "completed",
    abandoned = "abandoned",
    inProgress = "inProgress"
}
export enum WorkoutType {
    run = "run",
    other = "other",
    hiit = "hiit",
    yoga = "yoga",
    strength = "strength",
    walking = "walking",
    cycling = "cycling"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    abandonWorkout(workoutId: WorkoutId): Promise<boolean>;
    addComment(postId: PostId, content: string): Promise<boolean>;
    appendGpsPoint(workoutId: WorkoutId, coord: Coordinate): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    claimZone(zoneId: ZoneId, workoutId: WorkoutId): Promise<boolean>;
    clearConversation(): Promise<boolean>;
    coachTransform(input: TransformationInput): Promise<TransformationOutput>;
    completeWorkout(workoutId: WorkoutId, distanceMetres: number, durationSeconds: bigint, caloriesBurned: number | null, averagePaceSecondsPerKm: number | null, elevationGainMetres: number | null): Promise<boolean>;
    createCompetition(monthYear: string, challengeType: ChallengeType, prizes: Array<string>, startsAt: Timestamp, endsAt: Timestamp): Promise<CompetitionId>;
    createPost(workoutSummary: WorkoutSummary | null, territoryClaimed: Array<ZoneId>, message: string): Promise<PostId>;
    createProfile(username: string, displayName: string, fitnessLevel: FitnessLevel, locationLabel: string, weeklyAvailabilityHours: bigint): Promise<boolean>;
    createZone(name: string, polygon: Array<Coordinate>, areaKm2: number): Promise<ZoneId>;
    deletePost(postId: PostId): Promise<boolean>;
    follow(target: UserId): Promise<boolean>;
    getActiveCompetition(): Promise<CompetitionView | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCoachConversation(): Promise<Array<CoachMessage>>;
    getCoachHistory(): Promise<Array<CoachMessage>>;
    getCompetition(competitionId: CompetitionId): Promise<CompetitionView | null>;
    getCompetitionLeaderboard(competitionId: CompetitionId): Promise<Array<Standing>>;
    getFollowers(userId: UserId): Promise<Array<UserId>>;
    getFollowing(userId: UserId): Promise<Array<UserId>>;
    getGlobalFeed(limit: bigint, offset: bigint): Promise<Array<PostView>>;
    getLeaderboard(locationFilter: string | null, limit: bigint): Promise<Array<LeaderboardEntry>>;
    getMyFeed(limit: bigint, offset: bigint): Promise<Array<PostView>>;
    getMyProfile(): Promise<UserProfile | null>;
    getMyWorkouts(limit: bigint, offset: bigint): Promise<Array<WorkoutSummary>>;
    getPost(postId: PostId): Promise<PostView | null>;
    getProfile(userId: UserId): Promise<UserProfile | null>;
    getUserWorkouts(userId: UserId, limit: bigint, offset: bigint): Promise<Array<WorkoutSummary>>;
    getWorkout(workoutId: WorkoutId): Promise<WorkoutSummary | null>;
    getWorkoutRoute(workoutId: WorkoutId): Promise<Array<Coordinate> | null>;
    getZone(zoneId: ZoneId): Promise<ZoneInfo | null>;
    getZoneHistory(zoneId: ZoneId): Promise<Array<TakeoverEvent>>;
    getZoneLeaderboard(): Promise<Array<[UserId, number]>>;
    getZonesInBounds(swLat: number, swLng: number, neLat: number, neLng: number): Promise<Array<ZoneInfo>>;
    isCallerAdmin(): Promise<boolean>;
    joinCompetition(competitionId: CompetitionId): Promise<boolean>;
    likePost(postId: PostId): Promise<boolean>;
    listCompetitions(): Promise<Array<CompetitionView>>;
    listZones(ownerFilter: UserId | null): Promise<Array<ZoneInfo>>;
    logGpsEvent(workoutId: WorkoutId, gpsEvent: GpsEvent): Promise<boolean>;
    sendCoachMessage(content: string): Promise<string>;
    startCoachSession(): Promise<Array<CoachMessage>>;
    startWorkout(workoutType: WorkoutType): Promise<WorkoutId>;
    unfollow(target: UserId): Promise<boolean>;
    unlikePost(postId: PostId): Promise<boolean>;
    updateProfile(displayName: string | null, fitnessLevel: FitnessLevel | null, locationLabel: string | null, weeklyAvailabilityHours: bigint | null, bio: string | null, avatarUrl: string | null): Promise<boolean>;
}
import type { ChallengeType as _ChallengeType, CoachMessage as _CoachMessage, CoachMessageId as _CoachMessageId, Comment as _Comment, CompetitionId as _CompetitionId, CompetitionView as _CompetitionView, Coordinate as _Coordinate, FitnessLevel as _FitnessLevel, GpsEvent as _GpsEvent, MessageRole as _MessageRole, PostId as _PostId, PostView as _PostView, Standing as _Standing, TakeoverEvent as _TakeoverEvent, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, WorkoutId as _WorkoutId, WorkoutStatus as _WorkoutStatus, WorkoutSummary as _WorkoutSummary, WorkoutType as _WorkoutType, ZoneId as _ZoneId, ZoneInfo as _ZoneInfo } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async abandonWorkout(arg0: WorkoutId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.abandonWorkout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.abandonWorkout(arg0);
            return result;
        }
    }
    async addComment(arg0: PostId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async appendGpsPoint(arg0: WorkoutId, arg1: Coordinate): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.appendGpsPoint(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.appendGpsPoint(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async claimZone(arg0: ZoneId, arg1: WorkoutId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimZone(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimZone(arg0, arg1);
            return result;
        }
    }
    async clearConversation(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.clearConversation();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearConversation();
            return result;
        }
    }
    async coachTransform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.coachTransform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.coachTransform(arg0);
            return result;
        }
    }
    async completeWorkout(arg0: WorkoutId, arg1: number, arg2: bigint, arg3: number | null, arg4: number | null, arg5: number | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.completeWorkout(arg0, arg1, arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeWorkout(arg0, arg1, arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async createCompetition(arg0: string, arg1: ChallengeType, arg2: Array<string>, arg3: Timestamp, arg4: Timestamp): Promise<CompetitionId> {
        if (this.processError) {
            try {
                const result = await this.actor.createCompetition(arg0, to_candid_ChallengeType_n4(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCompetition(arg0, to_candid_ChallengeType_n4(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async createPost(arg0: WorkoutSummary | null, arg1: Array<ZoneId>, arg2: string): Promise<PostId> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(to_candid_opt_n6(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(to_candid_opt_n6(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async createProfile(arg0: string, arg1: string, arg2: FitnessLevel, arg3: string, arg4: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(arg0, arg1, to_candid_FitnessLevel_n13(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(arg0, arg1, to_candid_FitnessLevel_n13(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async createZone(arg0: string, arg1: Array<Coordinate>, arg2: number): Promise<ZoneId> {
        if (this.processError) {
            try {
                const result = await this.actor.createZone(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createZone(arg0, arg1, arg2);
            return result;
        }
    }
    async deletePost(arg0: PostId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async follow(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.follow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.follow(arg0);
            return result;
        }
    }
    async getActiveCompetition(): Promise<CompetitionView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveCompetition();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveCompetition();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoachConversation(): Promise<Array<CoachMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoachConversation();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoachConversation();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoachHistory(): Promise<Array<CoachMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoachHistory();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoachHistory();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompetition(arg0: CompetitionId): Promise<CompetitionView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompetition(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompetition(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompetitionLeaderboard(arg0: CompetitionId): Promise<Array<Standing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompetitionLeaderboard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompetitionLeaderboard(arg0);
            return result;
        }
    }
    async getFollowers(arg0: UserId): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowers(arg0);
            return result;
        }
    }
    async getFollowing(arg0: UserId): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowing(arg0);
            return result;
        }
    }
    async getGlobalFeed(arg0: bigint, arg1: bigint): Promise<Array<PostView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalFeed(arg0, arg1);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalFeed(arg0, arg1);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(arg0: string | null, arg1: bigint): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard(to_candid_opt_n39(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard(to_candid_opt_n39(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async getMyFeed(arg0: bigint, arg1: bigint): Promise<Array<PostView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyFeed(arg0, arg1);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyFeed(arg0, arg1);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWorkouts(arg0: bigint, arg1: bigint): Promise<Array<WorkoutSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWorkouts(arg0, arg1);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWorkouts(arg0, arg1);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPost(arg0: PostId): Promise<PostView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserWorkouts(arg0: UserId, arg1: bigint, arg2: bigint): Promise<Array<WorkoutSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserWorkouts(arg0, arg1, arg2);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserWorkouts(arg0, arg1, arg2);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkout(arg0: WorkoutId): Promise<WorkoutSummary | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkout(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkout(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkoutRoute(arg0: WorkoutId): Promise<Array<Coordinate> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutRoute(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutRoute(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getZone(arg0: ZoneId): Promise<ZoneInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getZone(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getZone(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getZoneHistory(arg0: ZoneId): Promise<Array<TakeoverEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getZoneHistory(arg0);
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getZoneHistory(arg0);
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getZoneLeaderboard(): Promise<Array<[UserId, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getZoneLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getZoneLeaderboard();
            return result;
        }
    }
    async getZonesInBounds(arg0: number, arg1: number, arg2: number, arg3: number): Promise<Array<ZoneInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getZonesInBounds(arg0, arg1, arg2, arg3);
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getZonesInBounds(arg0, arg1, arg2, arg3);
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinCompetition(arg0: CompetitionId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.joinCompetition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinCompetition(arg0);
            return result;
        }
    }
    async likePost(arg0: PostId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async listCompetitions(): Promise<Array<CompetitionView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCompetitions();
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCompetitions();
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async listZones(arg0: UserId | null): Promise<Array<ZoneInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listZones(to_candid_opt_n59(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listZones(to_candid_opt_n59(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async logGpsEvent(arg0: WorkoutId, arg1: GpsEvent): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.logGpsEvent(arg0, to_candid_GpsEvent_n60(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logGpsEvent(arg0, to_candid_GpsEvent_n60(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async sendCoachMessage(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendCoachMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendCoachMessage(arg0);
            return result;
        }
    }
    async startCoachSession(): Promise<Array<CoachMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.startCoachSession();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startCoachSession();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async startWorkout(arg0: WorkoutType): Promise<WorkoutId> {
        if (this.processError) {
            try {
                const result = await this.actor.startWorkout(to_candid_WorkoutType_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startWorkout(to_candid_WorkoutType_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async unfollow(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollow(arg0);
            return result;
        }
    }
    async unlikePost(arg0: PostId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikePost(arg0);
            return result;
        }
    }
    async updateProfile(arg0: string | null, arg1: FitnessLevel | null, arg2: string | null, arg3: bigint | null, arg4: string | null, arg5: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(to_candid_opt_n39(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n62(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n63(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(to_candid_opt_n39(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n62(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n63(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
}
function from_candid_ChallengeType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChallengeType): ChallengeType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_CoachMessage_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoachMessage): CoachMessage {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_CompetitionView_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompetitionView): CompetitionView {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_FitnessLevel_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FitnessLevel): FitnessLevel {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_MessageRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageRole): MessageRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_PostView_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostView): PostView {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_TakeoverEvent_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TakeoverEvent): TakeoverEvent {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutStatus): WorkoutStatus {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutSummary_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutSummary): WorkoutSummary {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutType_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutType): WorkoutType {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_ZoneInfo_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ZoneInfo): ZoneInfo {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CompetitionView]): CompetitionView | null {
    return value.length === 0 ? null : from_candid_CompetitionView_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WorkoutSummary]): WorkoutSummary | null {
    return value.length === 0 ? null : from_candid_WorkoutSummary_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PostView]): PostView | null {
    return value.length === 0 ? null : from_candid_PostView_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Coordinate>]): Array<Coordinate> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ZoneInfo]): ZoneInfo | null {
    return value.length === 0 ? null : from_candid_ZoneInfo_n50(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WorkoutId]): WorkoutId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CompetitionId;
    startsAt: _Timestamp;
    standings: Array<_Standing>;
    isActive: boolean;
    challengeType: _ChallengeType;
    prizes: Array<string>;
    monthYear: string;
    endsAt: _Timestamp;
}): {
    id: CompetitionId;
    startsAt: Timestamp;
    standings: Array<Standing>;
    isActive: boolean;
    challengeType: ChallengeType;
    prizes: Array<string>;
    monthYear: string;
    endsAt: Timestamp;
} {
    return {
        id: value.id,
        startsAt: value.startsAt,
        standings: value.standings,
        isActive: value.isActive,
        challengeType: from_candid_ChallengeType_n18(_uploadFile, _downloadFile, value.challengeType),
        prizes: value.prizes,
        monthYear: value.monthYear,
        endsAt: value.endsAt
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CoachMessageId;
    content: string;
    createdAt: _Timestamp;
    role: _MessageRole;
}): {
    id: CoachMessageId;
    content: string;
    createdAt: Timestamp;
    role: MessageRole;
} {
    return {
        id: value.id,
        content: value.content,
        createdAt: value.createdAt,
        role: from_candid_MessageRole_n25(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PostId;
    createdAt: _Timestamp;
    likedBy: Array<_UserId>;
    author: _UserId;
    message: string;
    territoryClaimed: Array<_ZoneId>;
    commentsCount: bigint;
    comments: Array<_Comment>;
    likesCount: bigint;
    workoutSummary: [] | [_WorkoutSummary];
}): {
    id: PostId;
    createdAt: Timestamp;
    likedBy: Array<UserId>;
    author: UserId;
    message: string;
    territoryClaimed: Array<ZoneId>;
    commentsCount: bigint;
    comments: Array<Comment>;
    likesCount: bigint;
    workoutSummary?: WorkoutSummary;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        likedBy: value.likedBy,
        author: value.author,
        message: value.message,
        territoryClaimed: value.territoryClaimed,
        commentsCount: value.commentsCount,
        comments: value.comments,
        likesCount: value.likesCount,
        workoutSummary: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.workoutSummary))
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _WorkoutId;
    status: _WorkoutStatus;
    completedAt: [] | [_Timestamp];
    startedAt: _Timestamp;
    userId: _UserId;
    territoryZonesClaimed: bigint;
    durationSeconds: bigint;
    caloriesBurned: [] | [number];
    averagePaceSecondsPerKm: [] | [number];
    distanceMetres: number;
    workoutType: _WorkoutType;
}): {
    id: WorkoutId;
    status: WorkoutStatus;
    completedAt?: Timestamp;
    startedAt: Timestamp;
    userId: UserId;
    territoryZonesClaimed: bigint;
    durationSeconds: bigint;
    caloriesBurned?: number;
    averagePaceSecondsPerKm?: number;
    distanceMetres: number;
    workoutType: WorkoutType;
} {
    return {
        id: value.id,
        status: from_candid_WorkoutStatus_n33(_uploadFile, _downloadFile, value.status),
        completedAt: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.completedAt)),
        startedAt: value.startedAt,
        userId: value.userId,
        territoryZonesClaimed: value.territoryZonesClaimed,
        durationSeconds: value.durationSeconds,
        caloriesBurned: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.caloriesBurned)),
        averagePaceSecondsPerKm: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.averagePaceSecondsPerKm)),
        distanceMetres: value.distanceMetres,
        workoutType: from_candid_WorkoutType_n37(_uploadFile, _downloadFile, value.workoutType)
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    bio: [] | [string];
    fitnessLevel: _FitnessLevel;
    weeklyAvailabilityHours: bigint;
    username: string;
    displayName: string;
    followersCount: bigint;
    joinedAt: _Timestamp;
    avatarUrl: [] | [string];
    totalTerritoryArea: number;
    locationLabel: string;
    followingCount: bigint;
}): {
    id: UserId;
    bio?: string;
    fitnessLevel: FitnessLevel;
    weeklyAvailabilityHours: bigint;
    username: string;
    displayName: string;
    followersCount: bigint;
    joinedAt: Timestamp;
    avatarUrl?: string;
    totalTerritoryArea: number;
    locationLabel: string;
    followingCount: bigint;
} {
    return {
        id: value.id,
        bio: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.bio)),
        fitnessLevel: from_candid_FitnessLevel_n44(_uploadFile, _downloadFile, value.fitnessLevel),
        weeklyAvailabilityHours: value.weeklyAvailabilityHours,
        username: value.username,
        displayName: value.displayName,
        followersCount: value.followersCount,
        joinedAt: value.joinedAt,
        avatarUrl: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.avatarUrl)),
        totalTerritoryArea: value.totalTerritoryArea,
        locationLabel: value.locationLabel,
        followingCount: value.followingCount
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ZoneId;
    polygon: Array<_Coordinate>;
    owner: [] | [_UserId];
    name: string;
    workoutId: [] | [_WorkoutId];
    claimedAt: [] | [_Timestamp];
    areaKm2: number;
    takeoverHistory: Array<_TakeoverEvent>;
}): {
    id: ZoneId;
    polygon: Array<Coordinate>;
    owner?: UserId;
    name: string;
    workoutId?: WorkoutId;
    claimedAt?: Timestamp;
    areaKm2: number;
    takeoverHistory: Array<TakeoverEvent>;
} {
    return {
        id: value.id,
        polygon: value.polygon,
        owner: record_opt_to_undefined(from_candid_opt_n52(_uploadFile, _downloadFile, value.owner)),
        name: value.name,
        workoutId: record_opt_to_undefined(from_candid_opt_n53(_uploadFile, _downloadFile, value.workoutId)),
        claimedAt: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.claimedAt)),
        areaKm2: value.areaKm2,
        takeoverHistory: from_candid_vec_n54(_uploadFile, _downloadFile, value.takeoverHistory)
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    newOwner: _UserId;
    workoutId: _WorkoutId;
    previousOwner: [] | [_UserId];
    takenAt: _Timestamp;
}): {
    newOwner: UserId;
    workoutId: WorkoutId;
    previousOwner?: UserId;
    takenAt: Timestamp;
} {
    return {
        newOwner: value.newOwner,
        workoutId: value.workoutId,
        previousOwner: record_opt_to_undefined(from_candid_opt_n52(_uploadFile, _downloadFile, value.previousOwner)),
        takenAt: value.takenAt
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mostDistance: null;
} | {
    mostTakedowns: null;
} | {
    mostWorkouts: null;
} | {
    mostTerritory: null;
}): ChallengeType {
    return "mostDistance" in value ? ChallengeType.mostDistance : "mostTakedowns" in value ? ChallengeType.mostTakedowns : "mostWorkouts" in value ? ChallengeType.mostWorkouts : "mostTerritory" in value ? ChallengeType.mostTerritory : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: null;
} | {
    assistant: null;
}): MessageRole {
    return "user" in value ? MessageRole.user : "assistant" in value ? MessageRole.assistant : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: null;
} | {
    abandoned: null;
} | {
    inProgress: null;
}): WorkoutStatus {
    return "completed" in value ? WorkoutStatus.completed : "abandoned" in value ? WorkoutStatus.abandoned : "inProgress" in value ? WorkoutStatus.inProgress : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    run: null;
} | {
    other: null;
} | {
    hiit: null;
} | {
    yoga: null;
} | {
    strength: null;
} | {
    walking: null;
} | {
    cycling: null;
}): WorkoutType {
    return "run" in value ? WorkoutType.run : "other" in value ? WorkoutType.other : "hiit" in value ? WorkoutType.hiit : "yoga" in value ? WorkoutType.yoga : "strength" in value ? WorkoutType.strength : "walking" in value ? WorkoutType.walking : "cycling" in value ? WorkoutType.cycling : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} | {
    elite: null;
}): FitnessLevel {
    return "intermediate" in value ? FitnessLevel.intermediate : "beginner" in value ? FitnessLevel.beginner : "advanced" in value ? FitnessLevel.advanced : "elite" in value ? FitnessLevel.elite : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CoachMessage>): Array<CoachMessage> {
    return value.map((x)=>from_candid_CoachMessage_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PostView>): Array<PostView> {
    return value.map((x)=>from_candid_PostView_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkoutSummary>): Array<WorkoutSummary> {
    return value.map((x)=>from_candid_WorkoutSummary_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TakeoverEvent>): Array<TakeoverEvent> {
    return value.map((x)=>from_candid_TakeoverEvent_n55(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ZoneInfo>): Array<ZoneInfo> {
    return value.map((x)=>from_candid_ZoneInfo_n50(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CompetitionView>): Array<CompetitionView> {
    return value.map((x)=>from_candid_CompetitionView_n16(_uploadFile, _downloadFile, x));
}
function to_candid_ChallengeType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChallengeType): _ChallengeType {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_FitnessLevel_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FitnessLevel): _FitnessLevel {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_GpsEvent_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GpsEvent): _GpsEvent {
    return to_candid_record_n61(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_WorkoutStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkoutStatus): _WorkoutStatus {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_WorkoutSummary_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkoutSummary): _WorkoutSummary {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_WorkoutType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkoutType): _WorkoutType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserId | null): [] | [_UserId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkoutSummary | null): [] | [_WorkoutSummary] {
    return value === null ? candid_none() : candid_some(to_candid_WorkoutSummary_n7(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FitnessLevel | null): [] | [_FitnessLevel] {
    return value === null ? candid_none() : candid_some(to_candid_FitnessLevel_n13(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    message: string;
    timestamp: Timestamp;
    eventType: string;
    accuracy?: number;
}): {
    message: string;
    timestamp: _Timestamp;
    eventType: string;
    accuracy: [] | [number];
} {
    return {
        message: value.message,
        timestamp: value.timestamp,
        eventType: value.eventType,
        accuracy: value.accuracy ? candid_some(value.accuracy) : candid_none()
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: WorkoutId;
    status: WorkoutStatus;
    completedAt?: Timestamp;
    startedAt: Timestamp;
    userId: UserId;
    territoryZonesClaimed: bigint;
    durationSeconds: bigint;
    caloriesBurned?: number;
    averagePaceSecondsPerKm?: number;
    distanceMetres: number;
    workoutType: WorkoutType;
}): {
    id: _WorkoutId;
    status: _WorkoutStatus;
    completedAt: [] | [_Timestamp];
    startedAt: _Timestamp;
    userId: _UserId;
    territoryZonesClaimed: bigint;
    durationSeconds: bigint;
    caloriesBurned: [] | [number];
    averagePaceSecondsPerKm: [] | [number];
    distanceMetres: number;
    workoutType: _WorkoutType;
} {
    return {
        id: value.id,
        status: to_candid_WorkoutStatus_n9(_uploadFile, _downloadFile, value.status),
        completedAt: value.completedAt ? candid_some(value.completedAt) : candid_none(),
        startedAt: value.startedAt,
        userId: value.userId,
        territoryZonesClaimed: value.territoryZonesClaimed,
        durationSeconds: value.durationSeconds,
        caloriesBurned: value.caloriesBurned ? candid_some(value.caloriesBurned) : candid_none(),
        averagePaceSecondsPerKm: value.averagePaceSecondsPerKm ? candid_some(value.averagePaceSecondsPerKm) : candid_none(),
        distanceMetres: value.distanceMetres,
        workoutType: to_candid_WorkoutType_n11(_uploadFile, _downloadFile, value.workoutType)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkoutStatus): {
    completed: null;
} | {
    abandoned: null;
} | {
    inProgress: null;
} {
    return value == WorkoutStatus.completed ? {
        completed: null
    } : value == WorkoutStatus.abandoned ? {
        abandoned: null
    } : value == WorkoutStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkoutType): {
    run: null;
} | {
    other: null;
} | {
    hiit: null;
} | {
    yoga: null;
} | {
    strength: null;
} | {
    walking: null;
} | {
    cycling: null;
} {
    return value == WorkoutType.run ? {
        run: null
    } : value == WorkoutType.other ? {
        other: null
    } : value == WorkoutType.hiit ? {
        hiit: null
    } : value == WorkoutType.yoga ? {
        yoga: null
    } : value == WorkoutType.strength ? {
        strength: null
    } : value == WorkoutType.walking ? {
        walking: null
    } : value == WorkoutType.cycling ? {
        cycling: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FitnessLevel): {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} | {
    elite: null;
} {
    return value == FitnessLevel.intermediate ? {
        intermediate: null
    } : value == FitnessLevel.beginner ? {
        beginner: null
    } : value == FitnessLevel.advanced ? {
        advanced: null
    } : value == FitnessLevel.elite ? {
        elite: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChallengeType): {
    mostDistance: null;
} | {
    mostTakedowns: null;
} | {
    mostWorkouts: null;
} | {
    mostTerritory: null;
} {
    return value == ChallengeType.mostDistance ? {
        mostDistance: null
    } : value == ChallengeType.mostTakedowns ? {
        mostTakedowns: null
    } : value == ChallengeType.mostWorkouts ? {
        mostWorkouts: null
    } : value == ChallengeType.mostTerritory ? {
        mostTerritory: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
